name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # Runs at 03:00 UTC every Saturday
    - cron: '0 3 * * 6'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Push Docker image
    strategy:
      matrix:
        tag: [debian-bullseye]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Docker Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.tag }}
          file: ${{ matrix.tag }}/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/dnsmasq:${{ matrix.tag }}
          push: ${{ github.event_name != 'pull_request' }}
